language: rust

# Cache built crates for much faster builds.
cache: cargo

notifications:
  email:
    on_success: never

env:
  global:
    - PROJECT_NAME=redis-throttle

matrix:
  allow_failures:
    - rust: nightly

  include:
    # Stable.
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu

    # Beta.
    - os: osx
      rust: beta
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu

    # Nightly.
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - bash ci/install.sh

before_script: 
  # Don't fail on failure to install because it's probably because the target
  # already exists.
  - (cargo install rustfmt || true)

script:
  - bash ci/script.sh

before_deploy:
  - bash ci/before_deploy.sh

branches:
  only:
    # Pushes and pull requests to the master branch.
    - master

    # IMPORTANT Ruby regex to match tags. Required, or travis won't trigger
    # deploys when a new tag is pushed. This regex matches semantic versions
    # like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/

deploy:
  provider: releases
  # Generated with `travis encrypt $token`. Token is scoped to `public_repo`.
  api_key:
    secure: "sK0Hy8dF1wmz+A505coJNeR8BYooD9AranRdvJagbvJcsijc1Bs7id8f0VruezSRvs2CZXt/iC9Btu/6/R+pvc7vskZyqsdXBpO1oFMUMwwzPuasz2w5DOFH8Ftg2fOl8Hjm3vzwp/itkjeUl/3beX/MTHt1emIusnFP6HcpSIx3XUvjU5c+VoAuGIj5qEu2eKGyRQf+pFiHqeR5H75cVJoFps0E8eaQbCV1XolX/sVHenaxYIaTb87xMUCV6k2VHWhAR5036+OJ02W1q9mAgChD83Ac/+j2Oq52hg2yyjYsLit0of7BJ1Rg0025yZd8dap4g9cW59/MO6jnUzOiX1uHvWXgOaAiktzrgHcw0zwZS6DyYzRkJ2AVAaYXrs/LdVQOECMAc1Flur0aS/OwaojMRK6MDLqLJ1nMjacSQl2loAu1XFhVum0RZQ37jXrdJxZK9+xj712WkbSmGoQvh1oJB631H4nPNOJxBOdvV3EL3sJ/XGVpXEWlQk28V6QPpxSCmNNDVNj3s1LuonkB+L6ZxreKixP2tWMO76a63k4zBBVaCDdkmIDCaXActDM/V3+nQbJgQBApu/v0+d0dd91P0uapWYkUOJMRVoGUVQ1xRPdCh/yaVRd6DPN4HW7TCaEUyamlcFo9mZsTiC6pTPNMv3IjpEgJfzf/3qkjryQ="
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  # Don't delete the artifacts from previous phases.
  skip_cleanup: true
  # Deploy when a new tag is pushed.
  on:
    # Channel to use to produce the release artifacts. NOTE make sure you only
    # release *once* per target.
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
